<a href="https://colab.research.google.com/github/MinseoMoon/aipython/blob/main/240503_%EC%88%98%EC%A0%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1부터 10까지(미포함)의 2걸음 크기의 정수값 배열을 생성해보자

In [ ]:
import numpy as np
arr=np.arange(1,11,2)
print(arr)

[1 3 5 7 9]


모양이 (3, 4)인 모든 값이 1인 배열을 생성해보자.

In [ ]:
arr=np.ones((3,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


0과 1사이를 10등분하고자 할 때 등분값 배열을 생성해보자

In [ ]:
arr=np.linspace(0,1,10)
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


A행렬을 생성해보자

In [ ]:
A = np.array(
 [[ 1, 2, 3, 4, 5],
 [ 6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20],
 [21, 22, 23, 24, 25]]
)

A의 모양(shape)을 출력해보자.

In [ ]:
print(A.shape)

(5, 5)


19 값을 추출해보자

In [ ]:
print(A[3,3])

19


슬라이싱을 이용하여 [[1, 2], [6, 7]] 값을 추출해보자

In [ ]:
print(A[:2,:2])

[[1 2]
 [6 7]]


슬라이싱을 이용하여 [[19, 20], [24, 25]] 값을 추출해보자

In [ ]:
print(A[3:5,3:5])

[[19 20]
 [24 25]]


슬라이싱을 이용하여 0축의 첫 번째 행과 두 번째 행을 추출해보자

In [ ]:
print(A[:2,:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


슬라이싱을 이용하여 1축의 마지막 열과 마지막 직전 열을 추출해보자

In [ ]:
print(A[:,-2:])

[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]
 [24 25]]


In [ ]:
#A행렬을 생성해보자.
arr=np.arange(1,37)
arr_3d=arr.reshape(3,3,4)
print(arr_3d)

#A 배열의 모양과 크기를 출력해보자.
print(arr_3d.shape)
print(arr_3d.size)

#A의 모양을 (3, 4, 3)로 변경해보자
a=arr_3d.reshape(3,4,3)
print(a)

#A를 1차원 배열로 구성해보자
print(arr_3d.flatten())

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]
(3, 3, 4)
36
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]
